version: '3.8'

services:
  flowerbingo:
    build: .
    container_name: flowerbingo-bot
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: python -u bot.py
    restart: unless-stopped

volumes:
  flowerbingo_db_data:
